name: Tests

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Install mops
        uses: ZenVoich/setup-mops@v1
      - name: Start dfx
        run: |
          dfx cache install
          dfx start --background
      - run: npm run setup
      - run: npm test
